version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: coastal-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: coastal-resilience
    volumes:
      - mongodb_data:/data/db
    networks:
      - coastal-network

  backend:
    build: ./backend
    container_name: coastal-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/coastal-resilience?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 7d
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      ML_SERVICE_URL: http://ml-service:8000
    depends_on:
      - mongodb
      - ml-service
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - coastal-network

  frontend:
    build: ./frontend
    container_name: coastal-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_SOCKET_URL: http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - coastal-network

  ml-service:
    build: ./ml-service
    container_name: coastal-ml-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
    networks:
      - coastal-network

volumes:
  mongodb_data:

networks:
  coastal-network:
    driver: bridge